name: mac builder
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04-arm
    # make sure these permissions are set so that
    # VS Code can connect to the machine
    permissions:
      actions: read
      contents: read
    steps:
    # ...
    - name: 🐛 Debug Build
      uses: stateful/vscode-server-action@v1
      if: true
      with:
        machineName: myMachine # optional, default: GitHub workflow run ID
        timeout: '3000000'       # optional, default: 30000
