name: linux gui2
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NGROK_TOKEN: 1hdFJmQC6iIak1eSbqx1t7Rrx56_2JLpasDVHybBixWv7Xftm
      PASSWORD: Secret123
    steps:
    - name: Set up RDP and SSH
      run: |
        sudo snap install ngrok
        sudo apt install xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils xrdp
        sudo adduser xrdp ssl-cert
        sudo systemctl restart xrdp
        echo "runner:$PASSWORD" | sudo chpasswd
        printf "authtoken: $NGROK_TOKEN\nregion: ap\n\ntunnels:\n  ssh:\n    proto: tcp\n    addr: 22\n  rdp:\n    proto: tcp\n    addr: 3389">>myconfig.yml
        ngrok start --config=myconfig.yml --all > /dev/null &
        sleep 2
        res=$(curl -s localhost:4040/api/tunnels)
        sshurl=$(echo $res|jq -r ".tunnels[] | select(.name==\"ssh\").public_url"|cut -c7-)
        rdpurl=$(echo $res|jq -r ".tunnels[] | select(.name==\"rdp\").public_url"|cut -c7-)
        while sleep 5; do printf "\n---------------\nSSH: $sshurl\nRDP: $rdpurl\nUSERNAME: runner\nPASSWORD: $PASSWORD"; done
        continue-on-error: true
