name: linux
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.2
    
    - uses: actions/checkout@v2
    - run: |
        source script-linux.sh
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
