name: mac
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: source script-mac.sh
    - name: setup android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
