name: mac
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: source script-mac.sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: MyArtifact
        path: |
          artifact/
          !artifact/out.md
        if-no-files-found: ignore
