name: mac simple
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - name: Installing TTY Share
      run: brew install tty-share
    - name: Setup TTY Share
      run: tty-share
    - name: Entering mainloop...
      run: tail -f /dev/null
