name: mac ci
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  Instance:
    runs-on: macos-latest
    steps:
    - name: Import Codesign Certificate
      id: codesign-cert
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.DIST_CERT_BASE64 }}
        p12-password: ${{ secrets.DIST_CERT_P12_PASSWORD }}
    - name: Import Healthshare Provisioning Profile
      id: prov-profile
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: ${{ secrets.BUNDLE_ID }}
        issuer-id: ${{ secrets.APPCONNECT_API_ISSUER }}
        api-key-id: ${{ secrets.APPCONNECT_API_KEY_ID }}
        api-private-key: ${{ secrets.APPCONNECT_API_KEY_PRIVATE }}
        profile-type: IOS_APP_STORE  
    - name: Installing requirement Apps
      run: |
        brew install ngrok --cask
        brew install code-server
        code-server --auth none>/dev/null &
        ngrok authtoken 3FqC8NZYFm3FCTnq31YP_4PVTJD76Ugzejfn5Eq49A
        ngrok http 8080 >/dev/null &
        sleep 7
        vsurl=$(curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)
        curl -X "PUT" "https://api.jsonbin.io/b/602b74834177c81b39c65b90" -H 'Content-Type: application/json' -H 'secret-key: $2b$10$DfHbA5X/E2M9cyKnpItQiO0TFYZG3D4O9XX/Cf1iOVS7Kpq1.gwWe' -d $'{ "url": "'"$vsurl"'" }'
    - name: Waiting for Agus
      run: |
        while ! test -f "/tmp/stopnow"; do
          sleep 10
        done
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: MyArtifact
        path: |
          artifact/
          !artifact/out.md
        if-no-files-found: ignore
