name: mac ci
on: 
  workflow_dispatch:
    inputs:
        api_issuer:
          required: true
        api_key:
          required: true
        api_private:
          required: true
        bundle_id:
          required: true
        dist_b64:
          required: true
        dist_pwd:
          required: true
        ngrok_token:
          required: true
        jsonbin_secret:
          required: true
defaults:
  run:
    shell: bash

jobs:
  Instance:
    runs-on: macos-latest
    steps:
    - name: Import Codesign Certificate
      id: codesign-cert
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ github.event.inputs.dist_b64 }}
        p12-password: ${{ github.event.inputs.dist_pwd }}
    - name: Import Healthshare Provisioning Profile
      id: prov-profile
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: ${{ github.event.inputs.bundle_id }}
        issuer-id: ${{ github.event.inputs.api_issuer }}
        api-key-id: ${{ github.event.inputs.api_key }}
        api-private-key: ${{ github.event.inputs.api_private }}
        profile-type: IOS_APP_STORE  
    - name: Installing requirement Apps
      run: |
        brew install ngrok --cask
        brew install code-server
        code-server --auth none>/dev/null &
        ngrok authtoken ${{ github.event.inputs.ngrok_token }}
        ngrok http 8080 >/dev/null &
        sleep 7
        vsurl=$(curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)
        curl -X "PUT" "https://api.jsonbin.io/b/602b74834177c81b39c65b90" -H 'Content-Type: application/json' -H 'secret-key: '"${{ github.event.inputs.jsonbin_secret }}"'' -d $'{ "url": "'"$vsurl"'" }'
    - name: Waiting for Agus
      run: |
        while ! test -f "/tmp/stopnow"; do
          sleep 10
        done
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: MyArtifact
        path: |
          artifact/
          !artifact/out.md
        if-no-files-found: ignore
