name: Mac Minimal

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Installing requirement Apps
      run: |
        brew install ngrok --cask
        brew install code-server
        code-server --auth none>/dev/null &
        ngrok authtoken ${{ secrets.NGROK_TOKEN }}
        ngrok http 8080 >/dev/null &
        sleep 7
        vsurl=$(curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)
        echo $vsurl
        sleep 5
        echo $vsurl
    - name: Waiting for Agus
      run: |
        while ! test -f "/tmp/stopnow"; do
          sleep 10
        done
