name: windows
on: 
  workflow_dispatch:
defaults:
  run:
    shell: powershell
jobs:
  build:
    runs-on: windows-latest
    env:
      NGROK_TOKEN: 1hdFJmQC6iIak1eSbqx1t7Rrx56_2JLpasDVHybBixWv7Xftm
      RDP_PASSWORD: Secret123
    steps:
    - name: Set up RDP
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive -Path ngrok.zip -DestinationPath C:\Desktop\
        C:\Desktop\ngrok.exe authtoken $Env:NGROK_TOKEN
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 0
        # Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $Env:RDP_PASSWORD -Force)
        (Get-WmiObject -class "Win32_TSGeneralSetting" -Namespace root\cimv2\terminalservices -ComputerName $env:COMPUTERNAME -Filter "TerminalName='RDP-Tcp'").SetUserAuthenticationRequired(0)
    - name: Creating Tunnel
      run: |
        Start-Job { & C:\Desktop\ngrok.exe tcp 3389 }
        Start-Sleep 2
        $url=(Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels").tunnels.public_url.Substring(6)
        echo "RDP HOST: $($url)"
        echo "USERNAME: runneradmin`nPASSWORD: $($Env:RDP_PASSWORD)"
        Start-Sleep 21600
      continue-on-error: true
      
        
