name: windows
on: 
  workflow_dispatch:
defaults:
  run:
    shell: powershell
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup RDP
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip
        .\ngrok\ngrok.exe authtoken $Env:NGROK_TOKEN
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $Env:RDP_PASSWORD -Force)
        Start-Job { & .\ngrok.exe tcp 3389 }
        # Start-Sleep 10
        # echo "RDP HOST: " (Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels").tunnels.public_url
        echo "User: runneradmin // Passwd: $($Env:RDP_PASSWORD)"
      env:
        NGROK_TOKEN: 1hdFJmQC6iIak1eSbqx1t7Rrx56_2JLpasDVHybBixWv7Xftm
        RDP_PASSWORD: Secret123
    - name: Entering mainloop
      run: |
        Start-Sleep 21600
        
